### ISSUE TITLE
Parameter of "ct_path"

### ISSUE THREAD

**Issue by fukuzawa-e** [ImKeTT/ZeroGen#1]
ct_path is default defined by "/npy_data/converter_table_glove.npy", but I cannot find such a file from the source.
Could you please tell me how to resolve this problem ?

**Comment by ImKeTT** [comment]
Thanks for you interest in our work. We provide the `converter_table_glove.npy ` data [here](https://drive.google.com/drive/folders/1XHviYZnrX3KNqSKvUwkoHsxmeSFP5Jgn?usp=sharing). Please follow our instruction (https://github.com/ImKeTT/ZeroGen?tab=readme-ov-file#data-and-model-weights) to accurately extract all the data.

If you have further questions, plz don't hesitate to ping me.

**Comment by ImKeTT** [comment]
Will close this issue soon if there's no further questions.
